// <auto-generated />
namespace Virgol_Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddSlider : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSlider));
        
        string IMigrationMetadata.Id
        {
            get { return "202307160540451_AddSlider"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
